### ISSUE TITLE
NPC - Trader [Question]

### ISSUE THREAD

**Issue by adexgold** [DenizenScript/Denizen-For-Bukkit#1009]
I would like to be able to make trader NPCs to only trade with people who have a certain flag, such as the Warrior guild trader will only work with those who are in the warrior guild and has the appropriate flag on their character, i am currently using the Cititrader plugin which i know is not updated in quite some time but it has been serving its purpose for me so far. 

So I was just wondering is that possible? Also which trader plugin should I use, is there any that work well with Denizen and offer the same or similar GUI that Cititrader uses?

**Comment by mcmonkey4eva** [comment]
We generally recommend people build their own shop code or use an existing Denizen-driven one... half because that's what we always do with every plugin question, and half because good trader plugins aren't commonly available.
Anyway, you can get it working like that with any system... just cancel the NPC click event if they don't have the flag, in theory. A well made plugin will accept this and not do the trade.

**Comment by adexgold** [comment]
Thanks for the reply, yes I watched your youtube video with the inventory GUI and saw the potential to make a pretty swell shop using that in a script. I might script something like that eventually, I was just curious what was possible with the other plugins, again thanks
