### ISSUE TITLE
Cuboids have a south east bug

### ISSUE THREAD

**Issue by AnthonyAMC** [DenizenScript/Denizen-For-Bukkit#1022]
Notable cuboids are being treated as if they are one block bigger to the south east.

**Comment by mcmonkey4eva** [comment]
I could sworn I /just/ fixed this.

**Comment by Talamar1** [comment]
I thought you did when I was having issues with people entering cuboids, you did a +1 on the one edge due to the event firing on the one edge and not the center.

**Comment by AnthonyAMC** [comment]
For what it's worth, the issue wasn't preset in dev-175

**Comment by mcmonkey4eva** [comment]
Which side is south east? Positive or negative on the axis?

**Comment by AnthonyAMC** [comment]
positive

**Comment by mcmonkey4eva** [comment]
Yeah this -> https://github.com/mcmonkey4eva/Denizen/commit/1534c0fd42cb685ec426c0d24214a6809b8b3c7e#diff-c531a5d82c5b99f963180fef0b7cf56bL255 -> Fix one bug, create another. *Sigh* I have no idea what to do.

**Comment by mcmonkey4eva** [comment]
I think it's fine as-is with the `+1`... if you want a 1-block wide cuboid, you do `cu@loc|loc`, if you want 2-wide, `cu@loc|loc.add[1,1,1]` and so on. You can easily create any size and it functions to contain both blocks input rather than only one of the two as you'd expect.

**Comment by Talamar1** [comment]
Does it have to do with + and - axis?  Should you be adding 1 to a neg axis?

**Comment by mcmonkey4eva** [comment]
No.
Like
123|4567|89
If you create a lineoid from 4 to 8, you get the above ^ because the separators are added at 4.0 and 8.0, not 8.9 or whatever. Adding 1 to the positive axis is essentially making it 4.0 and 8.999999... and thus 4 to 8 looks like 123|45678|9
If you add 1 to the negative side, you get 1234|5678|9 which now excludes '4'. If you subtract one from the negative side you get 12|45678|9 which now arbitrarily includes 3, one block more than you asked for.

**Comment by Talamar1** [comment]
That's what I was referring to, if the axis is neg, shouldn't you subtract from the low order number, this making your line -1-2-3|-4-5-6-7-8|-9

**Comment by mcmonkey4eva** [comment]
See my explanation above, but add `-` in front of every number. The explanation is otherwise the same.

**Comment by Talamar1** [comment]
but if they touch/cross the edge at 3 (in your example) then they have entered 4 (unless they hit 3.0 exactly) and therefore should be considered in 4.  The biggest question is, when does the "entered a square" fire when coming at it from the 4 cardinal directions, which edges trigger the event, then you know when you need to add/subtract 1 from the cuboid to trigger entering and exiting.

**Comment by mcmonkey4eva** [comment]
When a player's origin (The center location of their body, at their feet) touches the line at the end of a block, they are considered to have entered. Not the center of a block, not anywhere but the very edge of a block.
It's not a question of where on the block to trigger the entry, but which blocks to trigger the entry for.
In the example I used above, we want everywhere from block 4 to block 8 to trigger entry.
However, the origin of a block is not actually at its center, but at it's negative-most corner. To compensate for this, we add 1 on the positive-most block. So instead of going from 4.0 to 8.0 (effectively only including up to block 7) we go from 4.0 to 8.999999999999... (~9.0) therefore standing on block 8 is just as valid as standing on block 4.
Since most players will stand on 4.5, 8.5, etc. rather than .0, it becomes a simple math problem.
To include 8.5, do you limit at 8.0 or 9.0? 9.0, simple. To include 4.5 do you set the minimum at 4.0, 5.0, or 3.0? Simple, 4.0!
If we subtracted one from the negative corner of block 4, then standing on block 3 would be valid - which we don't want.
So, to compensate for math being an existent entity, we add 1.0 (0.99999...) to ensure that the block is fully covered.

**Comment by Talamar1** [comment]
Right, so then why is |Anthony| still having an issue?

**Comment by mcmonkey4eva** [comment]
@Talamar1 I assume he either didn't understand the above, or expected `cuboid.size == cuboid.max - cuboid.min`.
EG, you'd expect the size of 4 to 8 to be `8 - 4 = 4` right? Nope! it's `(8 - 4) + 1 = 5`. Because you have to include the "extra" block.

**Comment by AnthonyAMC** [comment]
All i know is that in the notables.yml file it is clearly marked as one cuboid, but in game it is behaving as described, for all things cuboid related. There's no reason that end users should have to account for this mystery block, nor should i be able to stand at a location that is not within a cuboid as defined in notables.yml and have the result of ```/ex narrate <player.location.cuboids>``` return as if i am.

An example from my notables.yml file:
```
dregions_test_kids-plot: -174,57,-250,test|-151,81,-224,test
```
![2015-04-30_19 06 41](https://cloud.githubusercontent.com/assets/2293589/7424158/20c10392-ef6c-11e4-909c-991df63a5808.png)

-150 70 -223 is not within that cuboid, yet it behaves as if it is.

**Comment by mcmonkey4eva** [comment]
That's... very odd. Maybe you're too close to an edge?

**Comment by AnthonyAMC** [comment]
I took the screenshot looking face down. The cuboid is within the depressed area, which i am clearly out of. This doesn't effect just enter/exit events, it's for everything cuboid related that i've tested.

**Comment by AnthonyAMC** [comment]
Also, here's another screenshot. I used ```<player.location.block>``` to get the location from which to find cuboids. Again, that location is not within the cuboid, but it reports that it is.
![2015-04-30_20 11 19](https://cloud.githubusercontent.com/assets/2293589/7424878/3a0fe062-ef75-11e4-9933-595c1eb5fb09.png)

**Comment by mcmonkey4eva** [comment]
... oh. Duh. Remove `.block` silly

**Comment by mcmonkey4eva** [comment]
And in the future, .block will be fine too.

**Comment by AnthonyAMC** [comment]
Cuboid seems to be working as expected now. Can close, unless you want it open for others to reference.

**Comment by mcmonkey4eva** [comment]
It's set to auto-close when the PR is pulled. Fairly standard practice, close automatically when the main release is patched.

**Comment by AnthonyAMC** [comment]
yeah yeah... shh.
