### ISSUE TITLE
Potion system is wack yo

### ISSUE THREAD

**Issue by Morphan1** [DenizenScript/Denizen-For-Bukkit#1078]
Using `/i potion:3 1 effect:speed power:1 duration:69` gives you a potion of swiftness with a 1:09 timer and +20% speed.
When you hold this potion and do `/ex narrate <pl.item_in_hand>`, Denizen narrates it as
`i@potion,2[potion=SPEED,1,false,false]`
which isn't very helpful at all. I need to be able to check the duration.
Also, if you add more potion effects to the same potion, Denizen doesn't see any of the others

Yet another problem is that if you do `/ex give i@potion,2` while still having the other item in your inventory, doing `/ex take <pl.item_in_hand>` with one of them in your hand takes whichever one is first in the inventory contents.

Please fix this, it's very annoying to not be able to manipulate potions correctly or efficiently.

**Comment by brainscript** [comment]
*@Morphan1  This is not related to Essentials, it's also possible with Vanilla commands.
I would rename the issue. :smile: The following is what I wrote in the issue referenced by you.*

Using the command `/give @p potion 1 8197 {CustomPotionEffects:[{Id:23,Amplifier:0,Duration:600}],display:{Name:"Saturation Potion"}}` I get what I want.
I used a healing potion as "base" because of the red :red_circle: color.
![2015-10-05_15 20 59](https://cloud.githubusercontent.com/assets/8706734/10281572/ab6b1976-6b75-11e5-9735-52e08f9d5d60.png)
If I now type `/ex give <player.item_in_hand>` I get a **normal instant healing potion**.
![2015-10-05_15 24 20](https://cloud.githubusercontent.com/assets/8706734/10281592/d55f094a-6b75-11e5-86f8-7e4309ed1a10.png)
Doing `/ex narrate <player.item_in_hand>` returns `i@potion,8197[display_name=Apple Juice;potion=INSTANT_HEAL,1,false,false]`. Replacing `INSTANT_HEAL` with `SATURATION` and then giving it to me also gives me **the wrong item**.

Please fix this bug! :smile:

**Comment by Morphan1** [comment]
@mcmonkey4eva I think I'm gonna break the current broken functionality and add just add a  config option that should be removed whenever 1.0 happens
`Use old broken potions system: false`

**Comment by mcmonkey4eva** [comment]
@Morphan1 Break anything enabled by default and I'll stab you `D:<`

**Comment by Morphan1** [comment]
```
<monkeybot> Found mechanism: potion_effects for dItem objects
<monkeybot>   Input: dList
<monkeybot>   Description: Sets the potion's potion effect(s).
<monkeybot>     Input is a formed like: Effect,Upgraded,Extended|Type,Amplifier,Duration,Ambient,Particles(,Color)|...
<monkeybot>     For example: SPEED,true,false|SPEED,2,200,false,true,red
<monkeybot>   Tag: <i@item.potion_effect[<#>]>  Returns the potion effect on this item. In the format Effect,Level,Extended,Splash 
<monkeybot>        <i@item.potion_effect[<#>].type>  Returns the type of the potion effect. 
<monkeybot>        <i@item.potion_effect[<#>].duration>  Returns the duration in ticks of the potion. 
```
