### ISSUE TITLE
Notable entities.

### ISSUE THREAD

**Issue by KeangDavid** [DenizenScript/Denizen-For-Bukkit#1106]
Have events like "on player right clicks entity:" able to be triggered with a saved entity. ie, "on player right clicks at COMMANDER:"

**Comment by mcmonkey4eva** [comment]
wut why

**Comment by KeangDavid** [comment]
The same reason you have any notables. To avoid a bunch of checks. Instead of checking a players location every time they change blocks to see IF they entered a "area" you can note an area and have the event only trigger for a specific area. Instead of checking what inventory a player has open every time some one clicks in an inventory you can note an inventory so you don't have to do, if player.inventory_open.is[!=].blah blah you can just have an event for on player clicks in specificInventory. Why not have it for entities. Why would entities not be able to be noted.

 Morphan pointed out that entities often don't stay very long. This is the case for normally spawned entities that are meant to be normal mobs. Even so that is just more reason to be able to note a mob, so you can keep track of a mob while it is spawned and despawned. There are is a ton of other things entities are used for with denizen as well. Something I'm working on is a 3rd person camera, as well as NPCs (Citizen has always been to buggy for me to want to use).

**Comment by mcmonkey4eva** [comment]
@Morphan1 what do you think?

**Comment by mcmonkey4eva** [comment]
@Morphan1 hellllooooo?

**Comment by Morphan1** [comment]
It sounds like it'd be useful I guess. I'm not sure how you would spawn a noted entity, though, when the server restarts. Would you be able to spawn multiple copies of it? Because then there's conflicting noted entities running around.

The only reasonable way I can think of is if we also save the location of the entity and spawn it when the server starts, which seems a bit weird. We'd also have to account for things like being leashed to a fence

**Comment by BlackCoyote** [comment]
Isn't the thing he wants exactly the same as using an entity script?

**Comment by Morphan1** [comment]
@BlackCoyote actually, for all intensive purposes, probably.

**Comment by mcmonkey4eva** [comment]
... Yup.
