### ISSUE TITLE
Add - power command

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Denizen-For-Bukkit#1144]
Used to power blocks (like dispensers and droppers and other blocks).

**Comment by brainscript** [comment]
:heavy_plus_sign::+1:

**Comment by mcmonkey4eva** [comment]
There's now a location 'activate' mech, which will activate dispensers and droppers. Other blocks can be added. Many other block types are better controlled by the 'switch' command.

Unfortunately it's not possible to make a truly generic power command (that just creates redstone power from nowhere) due to the way block power logic is built in minecraft.
