### ISSUE TITLE
Denizen AI Control

### ISSUE THREAD

**Issue by mcmonkey4eva** [DenizenScript/Denizen-For-Bukkit#1149]
It'd be cool if we took like... every little last variable an entity has, particularly related to AI, and make it controllable. In theory you can do crazy stuff. A basic example is toggle whether zombies bash down doors. A more fun example would be bashing down /other block types/ and so forth.

**Comment by brainscript** [comment]
:heavy_plus_sign::+1:

**Comment by Morphan1** [comment]
Dibs.

**Comment by Talamar1** [comment]
Don't you have events to convert?

**Comment by Morphan1** [comment]
Probably but this is much more fun.

**Comment by mcmonkey4eva** [comment]
@Morphan1 how's this coming?

**Comment by Morphan1** [comment]
This has always been a rather strange task to handle. From everything I gathered after looking into it when this issue was created, it seems that we'd need to pretty much tear apart entities completely and piece them back together, involving some maps and lists that by default we don't have access to. So that's fun

**Comment by Fortifier42** [comment]
Good luck sir, you dibbed it

**Comment by fullwall** [comment]
You'd have to poke into the internals of each minecraft AI goal.

**Comment by mcmonkey4eva** [comment]
This is probably better to just use Citizens for entities with non-standard AI.
