### ISSUE TITLE
Change script handling to abort on error

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Denizen-For-Bukkit#1246]
When a script runs into a script error, it should abort, not just go on.

Example:
```
- if <tag that returns pickle> { 
   - narrate "Wilbur"
   } else {
   - narrate "Ed"
   }
- narrate "eh?"
```
This should abort, this should not assume false and print
```
Ed
eh?
```

**Comment by mcmonkey4eva** [comment]
I was considering making a special case for this to happen, but definitely not all the time.

**Comment by Talamar1** [comment]
That way, certain people can stop returning nulls when it should be booleans >.>

**Comment by mcmonkey4eva** [comment]
@Talamar1 True, false, or error are all possible results of a boolean tag.

**Comment by Talamar1** [comment]
null is not boolean... thus my point, the system should error and not just let an invalid boolean value like null or anything else pass through the system.  As I argued with Fortifier, if you are going to call something a boolean, it has 2 return values, true or false, null is not a valid boolean.

**Comment by mcmonkey4eva** [comment]
null = error

**Comment by Talamar1** [comment]
null isn't error, or you aren't handling the error properly, null results in false.

**Comment by Fortifier42** [comment]
null invalidates the tag, causing the user to get an error in console, thus error.

**Comment by Talamar1** [comment]
It doesn't error the code, it prints an error message, there is a difference between error reporting and error handling.

**Comment by KeangDavid** [comment]
It would appear you want the script to fail purely due to semantics? Having it fail softly is probably better than just not working, due to the nature of the language. Many beginners will pick up denizen to try and learn something VERY complicated they have 0 experience with. Though there is no need to baby someone through their time learning how to script. There is also no need to have "Boolean" checks entirely stop the script if they are not exactly "true" or "false". Not to mention if you Require if checks to be either true or false that become EXTREMELY difficult due to the limitations of tags.
The method of 'if it is not true, then it is false' really keeps it simple for most users. You obviously would not personally have a problem with what you are suggesting but, what about every one else?

**Comment by Talamar1** [comment]
KeangDavid, teaching a user how to use Boolean properly is not babying them, its teaching them to use proper coding.  Meh, I'm done arguing this point.
