### ISSUE TITLE
New schematic 1.12 error

### ISSUE THREAD

**Issue by Noiknez** [DenizenScript/Denizen-For-Bukkit#1614]
Greeting,

http://prntscr.com/fr6ijp
The schematics command work fine before on 1.11.2, now the schematic command don't find the file in question, it create the schematic fine, but when it is to find it it does not work

I am using the Denizen developpment version on bukkit  #195 (2 juil. 2017 21:21:59)

**Comment by mcmonkey4eva** [comment]
lowercase the file name? Might be relevant

**Comment by Noiknez** [comment]
Tried with :
<to.uppercase>
<to_lowercase>
With the ex command directly (Uppercase and Lowercase)
same problem, it worked fine before 1.12

**Comment by mcmonkey4eva** [comment]
No, the FILE NAME.

**Comment by Noiknez** [comment]
The file name is already in lowercase : http://prntscr.com/fr70nd

**Comment by mcmonkey4eva** [comment]
I'm going to repeat `the FILE NAME` until you actually look at the file name, okay? okay.

**Comment by loa-in-** [comment]
mcmonkey4eva asks about the name of file as it is on disk.

In particular unless you're running your server on Windows
you need to match the file name toTheLetTer.YmL

If you're running the server software on Windows, it's still best
to keep consistent, as otherwise it'll break if you try to run it on other platforms.

Be advised, that platform on which the client is running doesn't matter, only server's.

**Comment by Noiknez** [comment]
Fixed
On windows : Uppercase and lowercase work
On linux : lowercase only work
