### ISSUE TITLE
"item_in_hand" does not set entity's held item to air when used in "spawn" cmd

### ISSUE THREAD

**Issue by MusicScore** [DenizenScript/Denizen-For-Bukkit#1692]
Spigot 1.12.2, Denizen Developmental build 268.

Whenever I try to use `spawn` to spawn in entities, the `item_in_hand` mec does not override the entity's default item_in_hand if I try to set the item_in_hand to air.

I've tested this on Skeletons and Vexes.

**Comment by mcmonkey4eva** [comment]
probably you have to do it afterwards in a separate command... it's a sequencing issues.
It's > spawn entity > run mecs > apply additional data
Which probably isn't the best way of ordering it but it'd be annoying to fix that, in part because of how the code is structured for that area, in part because the best fix would be switch to 4 parts, wherein some things the mec runs after but some things are applied further down the line still, because minecraft is minecraft.

**Comment by MusicScore** [comment]
Well, darn.

Oh well, I already have a working workaround. That's alright.
