### ISSUE TITLE
ERROR! Null player CraftOfflinePlayer[UUID=xxxxxxxxxxxxxxxxxxxxx]

### ISSUE THREAD

**Issue by kaiarne** [DenizenScript/Denizen-For-Bukkit#1732]
Sorry for a potential double post, I added this to https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1523, but I didn't see it was already close und I'm not sure if there will be any notification.

I've been trying Denizen for the first time and also get 2313 (25% of our total players) lines of this error at startup:
[12:50:10] [Server thread/INFO]: ERROR! Null player
CraftOfflinePlayer[UUID=6bd268ba-777e-4480-9151-41d65015cdde]

und 2315 (!) lines this error at shutdown.

[12:50:52] [Server thread/INFO]: ERROR! 'null' is having trouble deconstructing! You might
have a corrupt player file!

startup: https://pastebin.com/1gz08dwg

I did check the world data with Minecraft Region Fixer, no errors.
Our world and player data are up to 7 years old, though always converted succesfully. But it may be the case that those ca. 2000 players are players which have not logged on for some years, so some "field" in their data may be missing, which is autoamtically created for every online player.

Other plugins don't seem to have problems with the playerbase and their UUIDs (exzept LWC of course, but LWC is rather old nowadays).

I tried Denizen development from 2018-01-31, 2018-03-02 and the latest version from spigotmc

**Comment by mcmonkey4eva** [comment]
Yeah that basically tells you exactly what went wrong in one of those outputs - corrupt player files.

Each UUID listed is a player's UUID corresponding to a player file in your world folder that is corrupt.

Often this means at a minimum it doesn't have a valid name for that player. In some cases it means the file is entirely bad.
Either way, those players are likely ones who haven't been on your server in years...
(If they had connected since then, it would update the player file with properly corrected/updated info)
