### ISSUE TITLE
Entity Script Debug not working

### ISSUE THREAD

**Issue by uledrith** [DenizenScript/Denizen-For-Bukkit#1749]
debug: false on entity script containers produces the following error in console:

[13:33:14 INFO]:  ERROR! Invalid mechanism specified: debug

```
InjuredZombie:
  debug: false
  type: entity
  entity_type: e@zombie[<proc[Mob_Builder].context[zombie|trash|<script.name>]>]
```

However, if I remove the debug, then I get a bunch of spam (see below).  Seems to be a no win situation.  And yes, the referenced procedure script has 'debug: false' enabled.

[13:34:16 INFO]:  Filled tag
                   <proc[Mob_Builder].context[zombie|trash|INJUREDZOMBIE]> with
                   'health=15;equipment=i@air|i@iron_leggings|i@air|i@air;max_health=15;custom_name_visibility=true;custom_name=an injured zombie'.
[13:34:16 INFO]:  Filled tag <script.name> with 'INJUREDZOMBIE'.
[13:34:16 INFO]:  Adding definition %entitytype% as zombie
[13:34:16 INFO]:  Adding definition %entityquality% as trash
[13:34:16 INFO]:  Adding definition %entityname% as INJUREDZOMBIE
[13:34:16 INFO]:  Filled tag

**Comment by mcmonkey4eva** [comment]
That's a screwup on our part, the entity script engine assumed 'debug' to be a mechanism key because it's not a recognized key (I guess we just never tested with that key in use, as usually we don't have tags in an entity script...)

Note that if you're not taking advantage of the entity script container setup, you might choose to just not use an entity script and just do `<proc[injuredzombie]>` or something to return what you currently have as an entity type

**Comment by uledrith** [comment]
ok, i will just do everything outside of entity scripts for now then.  Thank you!

**Comment by mcmonkey4eva** [comment]
fixed in latest dev build
