### ISSUE TITLE
DisabledSlots mech/tag for Armor Stands

### ISSUE THREAD

**Issue by Rickytehduck** [DenizenScript/Denizen-For-Bukkit#1787]
We're currently missing a mech to disable slot interaction for armor stands.

https://minecraft.gamepedia.com/Armor_Stand/ED
https://www.reddit.com/r/Minecraft/comments/2czu1p/armorstand_disabledslots_flag_system/

**Comment by mergu** [comment]
yes yes

nbt

wonderful

**Comment by Morphan1** [comment]
How would you feel about something along the lines of
```
- adjust <def[armor_stand]> allow_remove:off_hand|false
- adjust <def[armor_stand]> allow_replace:off_hand|false
- adjust <def[armor_stand]> allow_place:off_hand|false
```
Basically, rather than dealing with arbitrary numbers (without even the proper binary math to help) it would be `allow_<type>:<slot>|<true/false>` where `<slot>` is defined here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/EquipmentSlot.html

**Comment by mcmonkey4eva** [comment]
How do you do multiple slots in that?

**Comment by Morphan1** [comment]
Well, could also do `slot/value|slot/value|...` like some other mechs

**Comment by mcmonkey4eva** [comment]
added in latest dev builds thanks to https://github.com/mcmonkey4eva/Denizen/pull/149
