### ISSUE TITLE
on entity death, entity_type is invalid  (NPC)

### ISSUE THREAD

**Issue by redshirt2** [DenizenScript/Denizen-For-Bukkit#1803]
EntityFightingEvents:
    type: world
    debug: false
    events: 
          on entity death:
                 - debug log "<context.entity.entity_type>: <context.entity.name> died!"
                 - debug log "<context.entity> died!"

error is simple:
ERROR in script 'ENTITYFIGHTINGEVENTS'! Tag <context.entity.entity_type> is invalid!

This happens when an NPC dies.
Player is ok.
Monsters are ok.

Yes I could use on NPC death.  Unfortunately, if I am trying to catch and sort entity_type it errors.

**Comment by redshirt2** [comment]
I did use a workaround, where I use if <context.entity.is_player> and is_npc before any use of entity.entity_type..

My thoughts are that I shouldn't have to.. but anyway

**Comment by redshirt2** [comment]
possibly related.  Here is a paste of debug where it shows the ERROR]: Could not pass event EntityDeathEvent to Denizen v1.0.3-SNAPSHOT (build 401)

http://old.mcmonkey.org/paste/48907

**Comment by mcmonkey4eva** [comment]
OP Issue: Likely caused by Citizens setting NPCs to be removed from the world immediately on death event. Not sure about how to best workaround that. As an attempt that I believe should be fine though not completely ideal, I've modified the script event to run earlier (theoretically: *before* Citizens picks up the event and deletes the NPC). Might be more ideal to ensure Citizens does that deletion *last* always, rather than moving Denizen to be earlier.

Error message: That issue is present because I inexplicably trusted @BloodEko with something at one point, which was clearly a terrible idea to trust him and I don't know why I did that.
I fixed that as well.

**Comment by redshirt2** [comment]
Both seem to be working  fine.  Thanks!

**Comment by BloodEko** [comment]
Aight, the error goes on my cap, as I made changes for an improved damager tracker.

I haven't considered that the bukkit "Player" object can also ba an npc , which leads the error while converting to a dPlayer. Now it's dEntity instead which picks the right object itself.
