### ISSUE TITLE
Notables not being saved.

### ISSUE THREAD

**Issue by xr001** [DenizenScript/Denizen-For-Bukkit#1806]
The following scripts have an issue with the notable inventories not being saved to the notable .yml. 

As soon as the server is reset, the scripts breakdown as they are no longer able to find the inventory or in the case of "Quest Journal" (see below) behaves strangely, such as the inventory's full name being cutoff. Travel Pack inventory fails to come up at all.

I have tried many things, saving, resetting, adding in <player.uuid> instead of just <player> but nothing seems to work. Again, even after resetting the notables.yml is still blank.

Scripts:
Quest Journal: https://one.denizenscript.com/haste/48963
Travel Pack: https://one.denizenscript.com/haste/48959

Debugs:
Quest Journal: http://old.mcmonkey.org/paste/48956
Travel Pack: http://old.mcmonkey.org/paste/48961

I am currently running the latest 1.13 build of Spigot and the current Dev Build of Denizen.

**Comment by SXRWahrheit** [comment]
Just because I had a similar issue recently, have you checked the permissions for the whole Denizen folder and its files and subfolders?

**Comment by xr001** [comment]
It's a hosted server, so it should have write and read access to the files.

**Comment by SXRWahrheit** [comment]
Should, sure. I recommend asking them to fix perms for your whole server, just in case. I had an issue with data saving recently and perms were the problem. It's good to rule it out, even if it doesn't end up being the fix.

**Comment by mcmonkey4eva** [comment]
Check your full log file for errors during startup sequence and shutdown sequence. An error in either of those can ruin your server's ability to retain saves.

Also, if you haven't already, consider setting a script like this:
```yml
autosave:
  type: world
  events:
    on system time hourly:
    - execute as_server "denizen save"
    - execute as_server "citizens save"
```
that will help ensure data is saved even if server crashes or fails to shutdown properly.

**Comment by xr001** [comment]
So I noticed that I am getting this in the console when I do /denizen save:
https://one.denizenscript.com/haste/49022

**Comment by mcmonkey4eva** [comment]
It looks like you have a corrupted notable inventory (hidden validator codes in the title were lost)

**Comment by xr001** [comment]
What steps do I need to take to rectify this?

**Comment by mcmonkey4eva** [comment]
Do you have any existing notable inventories that are retained in the notables save file (and perhaps are corrupted)? Do you have any scripts that might mess with inventory titles (not counting inventory script types that have their default title key set)

**Comment by MusicScore** [comment]
Can confirm existence of notable inventory bugs for 1.13, though specifically title bugs. Every restart seems to cut the title shorter, until eventually this glorious thing happens when you run the title tag while the inventory is still recognized as valid:
http://old.mcmonkey.org/paste/49326

Then restarting the server again makes the inventory bugged enough to not even open.
http://old.mcmonkey.org/paste/49327

What I did upon booting up a clean new test server:
`/ex note "in@generic[title=Quest Journal;size=27]" as:test_inventory`
`/ex narrate <in@test_inventory.title>`
`/ex inventory open d:in@test_inventory`
After every restart I only ran the last two commands.

I've noticed that the displayed title on the inventory (while you can still open it) doesn't match with the value the <inventory.title> tag returns.

**Comment by xr001** [comment]
This is still an issue in current Denizen builds. Notable Cuboids seem to work okay, I haven't tried anything else as of yet.

**Comment by mcmonkey4eva** [comment]
Fixed in https://github.com/mcmonkey4eva/Denizen/commit/470be7944c4104ca69bc57e24aea2a9036d4316e / build DEV-447+ on http://ci.citizensnpcs.co/job/Denizen_Developmental/
