### ISSUE TITLE
.points_between

### ISSUE THREAD

**Issue by LeafyMitsuwa** [DenizenScript/Denizen-For-Bukkit#1824]
The output of `/version` on my server is: 
git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-Snapshot)

The output of `/version denizen` on my server is:
1.0.3-Snapshot (Build 441)

(If relevant) A link to a paste of a script demonstrating the issue:
https://one.denizenscript.com/haste/50428

The issue is:
I think the ``points_between`` might be borked.

The test scenario is as such, where endstone is meant to be protected by the stained glass. The stained glass having its blast resistance altered to match obsidian.

In this scenario, the ``points_between`` detects the stained glass between the TNT and the Endstone:
https://i.imgur.com/lTCxhJt.png 

In this scenario, the ``points_between`` also detects the stained glass.
https://i.imgur.com/GmFoRp1.png

**Comment by mcmonkey4eva** [comment]
Did you hand-retype the version outputs? Copy/paste is preferred (or even screenshots). (I suspect retyping because the format is wrong).

I'm not sure what you expect the tag to do or what exactly it _is_ doing.
Either way: Be aware of _what a tag is_ when putting it to use. `points_between` is not `blocks_between`.
It makes no claim of being specific to block handling (blocks are pure-integer locations - arbitrary points can have decimals).
You probably want to add `.center` to block input locations (ie, `<def[value].center.points_between[<context.location.center>].`) to make it more readily able to handle blocks. (though there will still be imperfections in corner areas).

Also, don't forget general debugging techniques. That code is misbehaving, and you suspect points_between is giving you blocks it shouldn't be - output the exact values given by `points_between` and see why that might occur. You'll immediately notice the decimal values to start...
You have narrates to debug what your script is doing but not anything being done to decipher how it's doing it (which you suspect is going wrong).

Also, `[l@<def[value].simple>]` <-- that's just jank formatting.

Also, `material.name.is[==].to[<def[BlastProofBlocks]>]` <--that won't work at all. You can't compare if a text value is equal to a list (except if the text value happens to be an entire list represented as text for some reason)
