### ISSUE TITLE
<context.args.get[1]> in on command event not "null" anymore

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#1868]
Server version: build 494-DEV
Denizen version: version git-Spigot-29ab5e4-2bc7d1d (MC: 1.13.2)

The issue is: 

I finally updated to 1.13.2 and noticed that the tag <context.args.get[1]> in the event "on command" does not output "null" anymore when there is no list for <context.args>. Is this intentional or just missing yet?

**Comment by mcmonkey4eva** [comment]
That outputs an error, as it always has.
If you don't catch the error, your script will be errored and do whatever it ends up doing.

The simplest way to catch tag errors is with fallbacks, like so:
`<context.args.get[1]||null>`
(ie: if the tag fails, return `null` instead of erroring)

It is also recommended when possible that you avoid errors in the first place with logical checks, such as:
```
- if <context.args.size> == 0:
  - narrate "/mycommand [player] [smell]
  - queue clear
```
