### ISSUE TITLE
on player clicks in inventory event bug

### ISSUE THREAD

**Issue by WaterQuarks** [DenizenScript/Denizen-For-Bukkit#1872]
The output of `/version` on my server is: This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
The output of `/version denizen` on my server is: Denizen version 1.0.3-SNAPSHOT (build 500-DEV)

(If relevant) A link to a paste of a script demonstrating the issue:
Minimum reproducible example:
https://one.denizenscript.com/haste/51307

The issue is:
Output:
![screenshot from 2019-01-04 20-24-15](https://user-images.githubusercontent.com/28162761/50718601-54134f80-105f-11e9-8a5b-d5d439c81f09.png)

Debug logs:
https://one.denizenscript.com/paste/51306

**Comment by mcmonkey4eva** [comment]
You, uh, clicked in your own inventory. What's the issue?

**Comment by WaterQuarks** [comment]
Both <c.inventory> and <pl.inventory> return my inventory, that's correct. But only the <pl.inventory.list_contents> tag returns its contents. The <c.inventory.list_contents> returns an empty list.

**Comment by mcmonkey4eva** [comment]
Fixed in build DEV-523.

So the issue here is `<context.inventory>` when clicking in your own inventory _isn't your own inventory_. It's a Crafting Inventory (ie, a special pseudo-inventory representing the 4 crafting slots and the result box at the top of your inventory), it's just mislabeled as a player inventory because dInventory doesn't account for that.
The initial solution I wanted was to make dInventory support crafting inventories to prevent confusion.
... However, Spigot doesn't have a way to get a crafting inventory out of a player, except via that event, so that's not valid to do with dInventory.
So instead the patch is to just... make it _actually_ be a player inventory in this situation. dInventory now automatically converts crafting inventories to player inventories.

**Comment by mcmonkey4eva** [comment]
Update, for DEV-525:
I actually changed it around to the originally planned solution (swap it to clearly identify as a crafting inventory) but with the note that crafting inventories are NOT guaranteed to work consistently or persistently and may randomly revert into player inventories.
