### ISSUE TITLE
I can't tell if I have my hand.

### ISSUE THREAD

**Issue by FxRayHughes** [DenizenScript/Denizen-For-Bukkit#1893]
The output of `/version` on my server is: **paste here**
The output of `/version denizen` on my server is: **paste here**
(If relevant) A link to a paste of a script demonstrating the issue: **paste here**
The issue is:
**Describe your issue in full here**
宝箱开启:
    type: world
    debug: false
    events: 
        on item enchanted:
        - determine passively cancelled
        - if <player.item_in_hand||null> != i@bx:
          - narrate '<&e>请手持尘封的武器'
          - queue clear
        - else:
          - if <context.item.simple> != i@jfs:
            - narrate '<&e>请放置解封匕首在附魔台上'
            - narrate '<&e>服务器已禁止原版附魔,若需附魔需要用铁砧与附魔书结合'
          - else:
          - execute as_server "lang2 send <player.name> 群聊链接" 

I can't tell if I have BX in my hand.

**Comment by mergu** [comment]
```
The output of /version on my server is: paste here
The output of /version denizen on my server is: paste here
(If relevant) A link to a paste of a script demonstrating the issue: paste here
```

Please fill this information out (especially the 3rd one). We can't see indentation of your script if you just paste it. We need more information about this issue than "I can't tell if I have my hand" to help as well. We also need to see any related items scripts you have since you seem to be using them

Scripting help should be requested on our discord: https://discord.gg/Q6pZGSR

**Comment by mcmonkey4eva** [comment]
```
- if <player.item_in_hand.scriptname||null> != bx:
```
The `.scriptname` tag is useful here (assuming `bx` is an item script)
