### ISSUE TITLE
Can you help me with <math:> syntax?

### ISSUE THREAD

**Issue by Impalla69** [DenizenScript/Denizen-For-Bukkit#1901]
The output of `/version` on my server is: Paper Spigot 1.13.2 
The output of `/version denizen` on my server is: (the command is /denizen version for me) 1.0.3-SNAPSHOT (build 565-DEV), Core version: 1.30 (Build 190)
The issue is:
I want to use LN() and exponents, in my script. The problem is I want to use a rather long algorithm for pricing, and <math:> appears to barf when I try to use it. I also tried splitting it up, but I don't think it's being recognized properly. Can anyone help me with your syntax? 
`- define price <math:[1.000018^(<def[desiredBonus]>+<def[currentBonus]>)]/[LN(1.000018)-1.000018^(<def[desiredBonus]>)/LN(1.000018)]>`

**Comment by mergu** [comment]
Don't use the math tag, use safe tags we provide. Also, this issue tracker is for issues with the plugin itself. Script help should be requested on our discord: https://discord.gg/Q6pZGSR

**Comment by Impalla69** [comment]
Well that's too bad. I don't like discord.  I also don't know what "safe tags" are. :( 
Thanks anyway. I guess I'm just screwed and can't use denizen. :(

**Comment by mergu** [comment]
We provide scripting support on our public discord help channel. There's also a documentation bot there you and us can both query to find tags. It's much easier to provide live support in this manner. Again, this issue tracker is for issues/feature requests and not generally scripting help. If you decide not to use Denizen because of this, that's your own prerogative.

If you decide not to use discord for some reason, the best I can recommend is the documentation site. We have tags for all of the math operations you want to do: http://one.denizenscript.com/denizen/tags. Feel free to join the discord for further help.

If you're getting Denizen errors or would like to request a feature, feel free to do that here. Otherwise please close this issue when you get a chance

**Comment by mcmonkey4eva** [comment]
` (the command is /denizen version for me)`
No, it isn't. That's a different command. The command `/version <plugin>` is a basic spigot command. If that does not function properly, you have something on your server breaking vanilla commands. I recall hearing that CMI or something like that was overriding vanilla commands and generally causing damage to server stability - if you're using a plugin that does that stuff, get rid of it.

------

For reference, proper standard math tags look more like: `<def[desiredBonus].add[<def[currentBonus]>].div[<def[whatever]>]>`
