### ISSUE TITLE
Error in narrate (targets:<server.get_online_players_flagged[flagname]>) don't catch

### ISSUE THREAD

**Issue by DerbanTC** [DenizenScript/Denizen-For-Bukkit#1950]
Targets in narrate commands don't catch `targets:<server.get_online_players_flagged[ActivError]>` by alltime and generates sometimes errors.

The output of `/version` on my server is: **git-paper 622**
The output of `/version denizen` on my server is: **denizen 763-DEV**
**Script:**
https://one.denizenscript.com/haste/53972
**Submit:**
`line 381 and below`
https://one.denizenscript.com/paste/53971

**The issue is:**
Debug says they are Errors by an narrate command.
I used this event for an overview ingame what happened with my scripts.
By a debug I've detected that my script affects an error. 
**Note:**
Please ignore the other errors because the event need an error, and they are related to the other issue I has reported. Probably they are an another issue, or an intereferencing script and I have to figured them first out, thanks. Even it's not, and the other are the initializing, tell me ;)

**Comment by DerbanTC** [comment]
this submit includes the aboved script with `debug: true`, it slipped my mind
https://one.denizenscript.com/paste/53973

**Comment by mcmonkey4eva** [comment]
Please use `:` format in your scripts.
To see the `:` format, refer to the new text tutorials: https://docs.denizenscript.com/docs/basics-of-scripting/the-if-command.html
The error you've encountered is due to your usage of the legacy braces format, mixed with your text to output being `"-"` (which is mishandled by the legacy braces format)
