### ISSUE TITLE
Default the "Queue speed" setting in the configuration to 0s

### ISSUE THREAD

**Issue by waterquarks** [DenizenScript/Denizen-For-Bukkit#1998]
This would reduce excessive verbosity in both the run and inject commands by sparing the addition of "instantly"; I doubt this would make any script malfunction other than pretty old ones!

**Comment by SXRWahrheit** [comment]
This is a needless breaking change.

**Comment by waterquarks** [comment]
Why?

**Comment by SXRWahrheit** [comment]
It is a breaking change, and it is needless, therefore it is a needless breaking change.

**Comment by SXRWahrheit** [comment]
![2019-08-06 13_05_57-Window](https://user-images.githubusercontent.com/774463/62564718-fe985e80-b84a-11e9-8816-601405698e6d.png)

**Comment by mcmonkey4eva** [comment]
This is pretty much set that way because of back support of historical scripts.
... It's been a while since that was the norm to use.
Most of the time, the usage is for interact scripts, as such I've split the setting into two options:
Global queue speed (run command, mainly) and interact script queue speed.
The global setting is now `instant` by default (won't affect existing servers, only newly generated config files), but interact scripts retain the `0.5s` setting for the time to avoid breaking legacy support.
