### ISSUE TITLE
Sidebar line(s) args are ignored

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/Denizen-For-Bukkit#2019]
CraftBukkit Version: git-Spigot-1a3504a-84f3da3 (MC: 1.13.2)
Denizen Version: Core: 1.50-SNAPSHOT (Build 360), CraftBukkit: 1.1.0-SNAPSHOT (build 4084-DEV)

Debug: https://one.denizenscript.com/paste/57654#34
Script in use: https://one.denizenscript.com/haste/57655

`/ex sidebar set "line:2|4" "value:Cake|Fun"` replaces the entire sidebar instead of only the lines.
`/ex sidebar remove "lines:2|4|6"` removes the entire sidebar

Also the arguments for the sidebar command seems to be a mess. Perhaps its the usage in the documentation that is outdated?

**Comment by mcmonkey4eva** [comment]
Oh yeah old meta. `scores` not `lines`.
`lines:` is still accepted though, doesn't break.

`/ex sidebar set "line:2|4" "value:Cake|Fun" replaces the entire sidebar instead of only the lines.`
Set _sets a new sidebar_. Use add/remove to change individually. I'd recommend just using a consistent sidebar regenerator script. Alternately, you can also use `<PlayerTag.sidebar.lines>` with some list operation tags.
This behavior (`set` option in `sidebar`) used to be inconsistent, and was corrected a few months ago.
