### ISSUE TITLE
Various recipe bugs and feature requests

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#2038]
```
> version
[03:44:39 INFO]: This server is running Paper version git-Paper-192 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[03:44:39 INFO]: Checking version, please wait...
[03:44:39 INFO]: Previous version: git-Paper-159 (MC: 1.14.4)
[03:44:39 INFO]: You are running the latest version
> version Denizen
[03:44:48 INFO]: Denizen version 1.1.0-SNAPSHOT (build 4157-DEV)
[03:44:48 INFO]: Author: The DenizenScript Team
> pl
[03:44:51 INFO]: Plugins (1): Denizen
```

Been writing some useful scripts to handle recipe books automatically, but noticed some issues:

- The very first time you create an item script with a recipe, you are unable to correctly discover the recipe via discover_recipe until you log off and back on. Discovering the recipe via the mec (NOT crafting the item ingame) before relogging will list the recipe in <player.discovered_recipes> but you will be unable to access it via your recipe book. Denizen may need to send a recipe update packet if this is a Spigot bug.
- You are unable to forget custom recipes that no longer exist after a script reload. They still appear in the recipe book but cannot be interacted with. A relog, as in the last case, fixes this. Ideally we should have a pre-script-reload event to handle doing old recipe cleanup there.

Example script showing both bugs:
```yaml
    on script reload:
    - announce "Reloading denizen scripts... reapplying custom recipes"
    - define items <server.list_scripts.filter[container_type.is[==].to[ITEM]].parse[name.as_item]>
    - foreach <server.list_online_players> as:player:
      # This will NOT remove recipes that were deleted
      - adjust <[player]> forget_recipe:<[player].discovered_recipes.filter[starts_with[denizen]]>
      - foreach <[items]> as:item:
        # This will NOT show new recipes to online players immediately (they need to relog)
        - adjust <[player]> discover_recipe:<[item].recipe_ids>
```

EDIT: Another bug, may be related to those above:
- Same-id recipe updates do not take effect on script reloads in the recipe book when doing a forget & re-discover

Feature requests:
- Mentioned pre-script-reload event or another solution to the above issue
- Tag access to cleanseNamespaceID method OR support getting recipe ids for item scripts with `no_id: true`. An item script recipe result cannot be used in other crafting recipes unless no_id is used.
- <server.list_recipes[(type)]> to retrieve a list of all recipes the server is aware of, with optional crafting interface type
- Cancellable recipe popups. Recipe cleanup on script reloads and relogs show a bunch of notifications. I'm not sure if the discord-discussed packet can prevent this, but if it can then I would much rather those notifications not show up. https://wiki.vg/Protocol#Unlock_Recipes
- Multiple recipes for the same item script should fall under the same "group", so that they are displayed in the recipe book as the same craftable item instead of 2 different items (my assumption is the group is what controls this, at least):
![image](https://user-images.githubusercontent.com/29823405/65312307-3b50b880-db60-11e9-82fc-22bb427d1cac.png)
![image](https://user-images.githubusercontent.com/29823405/65312343-4b689800-db60-11e9-9a20-85157d3dc672.png)
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ShapedRecipe.html#setGroup-java.lang.String-
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ShapelessRecipe.html#setGroup-java.lang.String-

**Comment by mcmonkey4eva** [comment]
For no_id items: set a custom recipe_id instead of using defaults, so you can know&guarantee the IDs (can even process them with a yaml_key tag).

list_recipe_ids added via https://github.com/DenizenScript/Denizen/commit/e35798ebe76f72d5e600be75274839c83407ab94

For the popup thing: Going to treat that as separate, and suggest you open a separate issue for that - ideally try to actually figure out the packet thing first.

Groups: They're all supposed to be under the default group of "custom", but that was mistakenly left out from shaped recipes specifically - fixed that.

For recipe book not being updated when scripts are reloaded: Well... yeah, reconnect if you do that and want the recipe book to be updated.

A pre-reload event: That ... sorta could be made, but the benefit of it is questionable, and the side consequences+bad implications are high. (For example: it would not be reliably fired, due to server restart or crashing both qualifying as a 'reload' technically).

Treating this issue as resolved. Open individual issues for anything not sufficiently resolved.
