### ISSUE TITLE
attach_to not functioning

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/Denizen-For-Bukkit#2084]
Server Software: paper233
Dev build 4440
Pretty straight forward to reproduce:
`/ex spawn spider`
`/ex <player.location.find.entities[spider].within[3].get[1]> attach_to:<player>`
When tested with another player, we had odd results.
player1 (`<player>`): saw no difference, and the spider behaved as any normal spider would.
player2 (just an observer): saw the spider stuck in place, just spinning around (rotation for player2 matches the spider's rotation for player1)

**Comment by mcmonkey4eva** [comment]
An entity cannot be attached to a player in that player's own view.
Similar, a player cannot be attached to an entity in that player's own view.
Attach_To just does not work that way, due to... _Minecraft_ just not working that way (fully clientside player movement). (Though to be fair, it would still be impossible to be *perfect* in almost any game, due to inherent network latency).

As for the observer not seeing the attachment:
What is the specific limitations of this issue? Is it specific to when the attached entity is a spider? Or do other entities also bug? Is it specific to when the entity is attached to a player, or do other attach targets bug?

**Comment by mcmonkey4eva** [comment]
Closing due to lack of reply, will reopen when requested answers are given.
