### ISSUE TITLE
Shield event and tags

### ISSUE THREAD

**Issue by Nakigoee** [DenizenScript/Denizen-For-Bukkit#2104]
Currently there is no way to know if a player is using a shield or not. 

It would be nice if we had something such as:

"On player starts/stops/toggles using shield"

And a boolean tag for checking if a player is using a shield or not.

**Comment by mcmonkey4eva** [comment]
`Currently there is no way to know if a player is using a shield or not.`
There is a way, and that would be `<PlayerTag.is_blocking>`

**Comment by mcmonkey4eva** [comment]
There doesn't appear to be an underlying event in Spigot, and the Spigot forums suggest just using the click events and figuring it out from there.

We might be able to hack together a better event via packet stuff, not sure...

**Comment by mcmonkey4eva** [comment]
I hacked in a packet-driven shield toggle event, after discovering that:
hold up shield = PacketPlayInBlockPlace
put shield down = PacketPlayInBlockDig
(Minecraft is stupid)

`on player raises/lowers/toggles shield`

Note that this is very imperfect, as there are a variety of odd cases. I've tried to catch the reasonable ones (if a player quits, dies, changes held item, drops the shield item, ... I added handlers that will still fire it).
I've been able to perform a case that doesn't get detected that honestly I'm of a mind should be considered a Minecraft bug and either way I'm not going to try to account for it because wtf:

If you have multiple shields in your hotbar, you can raise one shield, then swap to another shield. This will mean you're now holding a _lowered_ shield, and the 'lowers' event fires accordingly.
However... if you *keep holding* the right mouse button even while switching, no other shields will raise... but if you scroll back to the original shield item, it will automatically be raised again, without refiring the relevant packet. This is some form of ridiculous nonsense and I refuse to acknowledge its existence by trying to workaround the event firing for that specific case. I'm sure there are more stupid weird cases like it either way.

Demonstration gif of that nonsense for reference:
![wtf](https://i.alexgoodwin.media/i/misc/c20a28.gif)
