### ISSUE TITLE
Add LocationTag.find_structure[...] tag

### ISSUE THREAD

**Issue by mergu** [DenizenScript/Denizen-For-Bukkit#2114]
Would be nice to have a tag to get the location of the nearest structure using minecraft's internal logic. Based on the spigot api, looks like input would have to be something comma/tag separated as you have the structure type, a radius, and whether that structure has been explored: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#locateNearestStructure-org.bukkit.Location-org.bukkit.StructureType-int-boolean-

IMO it makes more sense as a location tag, where the location is the origin.

**Comment by mcmonkey4eva** [comment]
Implemented as `<LocationTag.find.structure[<type>].within[<#.#>]>` and `<LocationTag.find.unexplored_structure[<type>].within[<#.#>]>`

Figured it made the most sense to fit in with the existing `find.x` tags, as weird as they are, since it's mostly the same concept (even though it means adding more to the eventual rewrite of that tag structure, which I still don't know how to approach properly).

Side note: the StructureType class is ridiculous internally. It's a handmade imitation-enum where the registered names don't quiiiite match the name used in fields.
`WOODLAND_MANSION` field is registered as name `mansion`  (with specifically lowercase too).
Argh.

As a result of the above, the only "true" listing of structure types will be via `<server.list_structure_types>`.
