### ISSUE TITLE
.material tag returns m@white_banner for damaged shield

### ISSUE THREAD

**Issue by Xericore** [DenizenScript/Denizen-For-Bukkit#2157]
Hi, 

git-Paper-120 (MC: 1.15.2)
Denizen version 1.1.2-SNAPSHOT (build 1702-REL)

**Steps to reproduce:**

1.   Hold an undamaged shield in your main hand.
2.   /ex narrate <player.item_in_hand.material>
3.   See output: m@shield
4.   /ex inventory adjust slot:<player.held_item_slot> "durability:100"
5.   /ex narrate <player.item_in_hand.material>
6.   See output: m@white_banner[direction=SOUTH]

**Expected result for damaged shield:**
- m@shield

**Note:** The problem is only with the .material tag. <player.item_in_hand> for damaged shield is shown as expected:
   /ex narrate <player.item_in_hand> --> i@shield[durability=100]

**Comment by mcmonkey4eva** [comment]
This is effectively a Spigot issue, unfortunately. Spigot treats Shield items as having a BlockState of a banner block, instead of something sane like putting banner-color methods on a shield item.

The only things we can do about it are:
Option A: beg Spigot team to make a sane API instead of that awful hack
Option B: Add a ridiculous specific special case to how Denizen handles item materials to counteract that.
