### ISSUE TITLE
Discord Appeal

### ISSUE THREAD

**Issue by MrStreeet** [DenizenScript/Denizen-For-Bukkit#2421]
Hello, is it possible to get a ban appeal from Discord? I was a kid when I got banned form the server and I really want to appeal to join again to the server, could be possible? Thank you very much

**Comment by mcmonkey4eva** [comment]
You were banned for 2 years after you were caught lying and attempting to circumvent the ban. This is our maximum ban duration, reserved for those that do things like lying about moderation incidents as you did.
If you had been honest with us after the initial incident, you would not currently be banned - or if you did get banned, your ban would have already expired by now.
Unfortunately dishonesty makes it extremely difficult to trust any ban appeal.

If you have put in the effort to improve yourself as a person since that happened in 2021-October, you may rejoin 2023-October-12 and make your case then.
