### ISSUE TITLE
QUESTION: Future of Denizen

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#846]
Since i am not around in times when mcmonkey or aufdemrand are there i wanted to ask, what the plans for denizen are now that bukkit is probably lost?

What will happen with denizen? Are you moving to Sponge? Is it realistic to move to Sponge?

**Comment by Morphan1** [comment]
@mcmonkey4eva Where is the core as of now in terms of being able to begin coding for other server brands? And now that we know the Spigot team is going to continue development, are we even still seriously considering this? What other brands that are already up and stable could we branch out to to possibly expand our community?

If we're unsure about any of these things, we should really get together and figure this stuff out. It's been months since the fall of Bukkit, and although it isn't completely crashed and burned we <b>do have a system now to expand with</b>. Why limit to Bukkit/Spigot if we're capable of more?

**Comment by mcmonkey4eva** [comment]
It's a fully functional core, it works fantastically. It still needs some upgrades (moving a few simple commands coreward) but for the most part it's ready to be implemented elsewhere.

and I still consider Sponge a good thing to build for, as it's quite popular even now.

**Comment by AnthonyAMC** [comment]
Denizen-for-Voxalia!

**Comment by Morphan1** [comment]
That's called Frenetic

**Comment by GomaTerzu** [comment]
I lost track of the Sponge-development. Did they release a version you can work with now? Is Sponge still an option?

**Comment by Morphan1** [comment]
Sponge is still in heavy development, but we could theoretically start coding for it at any time.

**Comment by mcmonkey4eva** [comment]
It's pretty limited ATM, I don't want to bother with it yet. Maybe in 1.9 we'll start.

Until then, Spigot is best for now.

**Comment by GomaTerzu** [comment]
I'm going to close this since the Sponge Development was - in my opinion - way slower than expected and went a direction that I don't really like with Forge and I think I won't switch anytime soon.

**Comment by mcmonkey4eva** [comment]
I'd like this to be left open as information for anyone who wants to come reading about our plans.

Regardless of your personal interest in Sponge, we still intend to (Eventually) make a version for it.

I'd like to note that Sponge has a Vanilla version too, not just Forge, and ideally Denizen will work on both platforms.

**Comment by AsylumDreams** [comment]
Just a check to see if there's anything new re Sponge and Denizen ^_^

**Comment by mcmonkey4eva** [comment]
So for an update on this status.

We've analyzed Denizen's attack plan and there is a danger. Shall we have your shuttle on standby?

**EHEM** I mean, er, ...

Denizen 1 has some flaws weakening its beautiful core concepts.

As such, we are totally rewriting Denizen as Denizen2 on Sponge, specifically reoptimized for maximum speed/efficiency without in any way abandoning its ease of use.

Most of the changes will be core-side (IE, things you won't see while writing scripts), but since we're working with a different platform, the micro-details as well. By which I mean, some things like the names of tags may end up being different that they were on Bukkit.

AT THE SAME TIME, Denizen 1 (Bukkit edition) sails ever forward and will not be abandoned until we are 100% sure Bukkit/Spigot is no longer a viable platform.

**Comment by mcmonkey4eva** [comment]
Update:
Denizen2Sponge project is here https://github.com/DenizenScript/Denizen2Sponge and that readme links to the other components (Denizen2Core, etc).
If you want to run D2S right now, we highly recommend chatting with us on Discord: https://discord.gg/Q6pZGSR where we can help you get started - and you can help us shape development directions (building the D2 features you need as priority) 

Also D1 on Bukkit is still really strong, especially with the most recent core upgrades.
