### ISSUE TITLE
Slow Changes in "adjust item_message" mech (maybe Mojangs fault too)

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#950]
So I made a script like this:

http://hastebin.com/mezuxiyowo.xml

The script works fine, but there is one problem. The adjust item_message mech that shows how much bullets are left shows the amount only every second time. Even if i wait between two shots: So it looks like

MP5
MP5 28/30
MP5
MP5 26/30

What could be the reason?

**Comment by mcmonkey4eva** [comment]
@Morphan1 any ideas?

**Comment by Morphan1** [comment]
I'd recommend staying away from item_message altogether, as:

1. It doesn't work properly in Creative mode, as the item name is permanently changed by the client.
2. It resets the item name if you interact with the item because the server sends an update packet.
3. It's annoying to look at the stained glass when you have no item in your hand.
4. The message cannot easily be put on a repeat to enable it to stay properly for a set amount of time.

There's not a whole lot we can do to combat these internal weaknesses...

However, I'd look into the action_bar mechanism. It shows in the same location as Jukebox songs - just above the item display name.

**Comment by GomaTerzu** [comment]
Yeah after I discovered that the action_bar was added I change everything from item_message to action_bar and now it works very smooth. Thanks!
