### ISSUE TITLE
Problems with the shoot command

### ISSUE THREAD

**Issue by GomaTerzu** [DenizenScript/Denizen-For-Bukkit#966]
Hi, at the moment I am fighting with several different problems in the shoot command which I can't seem to overcome. I created a gun (nether fence) with bullets (snowball).

1. gravity, lead, height
These 3 options seem to have no effect. I tried it like this, and changing the values has no effect on the bullet:

`- shoot snowball shooter:<player> origin:<player.location.add[0,1.2,0]> speed:4 script:MP5Damage gravity:200.0 height:500.0 spread:30.0`

Maybe I am using them in a wrong way? I know that I was able to use gravity and height to achieve some kind of arrow effect. But I don't know how long ago this was. ALso what exactly is `lead:`?

2. speed
The speed option works fine up to `speed:4` but everything above 4 makes it look like the bullet does not hit the target anymore, but actually it still does. Only the snowball entity flys away in the wrong direction. See this screenshot:

http://oi61.tinypic.com/34qplx1.jpg

Is there a solution for this? I heard that this was maybe a bukkit/spigot issue?

3. falling_block as entity

When i use the shoot command to shoot falling blocks like grass for example I have the problem, that I can't deal damage anymore because you can't hit any entity with them. I guess that this is a MC issue because there is no event for that. The bigger problem is that the falling blocks get placed as solid blocks in most cases instead of just disappearing. Also they get placed pretty randomly around the hit location. Maybe you can add an option to prevent this?

`- shoot falling_block,grass`

4. shooting down on targets

My script looks like this (just testing)

"MP5 Shoot and Reload":
    type: world
    debug: off
    events:
        On player right clicks with i@MP5:
              - shoot snowball shooter:`<player>` origin:`<player.location.add[0,1.1,0]>` speed:4 script:MP5Damage spread:0 gravity:0 height:0

"MP5Damage":
    type: task
    debug : on
    script:
        - narrate "Hit `<def[hit_entities].formatted>`"
        - narrate "Target Location `<def[location].simple>`"
        - narrate "Player Location `<player.location.simple>`"
        - hurt 8 entities:`<def[hit_entities]>`

So when i shoot from around the same level at a target it works fine:

http://oi58.tinypic.com/oirbcl.jpg
http://oi57.tinypic.com/wlvj95.jpg

But when I stand on a roof and the distance is even smaller between me an my target this happens: The target list is simply empty and the hit location is the player.location. I also have a script where you throw molotow cocktails, but due to this problem they just explode at your location, when you try to throw/shoot them at enemies below your level.

http://oi60.tinypic.com/2822n7n.jpg
http://oi59.tinypic.com/2v0n5gi.jpg

Is there anything you can do? Is there any way to change my script so that i can shoot down from rooftops?

5. spread with multiple "bullets"

Now I also tried to use the spread option with multiple Entities:

`- shoot snowball|snowball|snowball|snowball|snowball shooter:<player> origin:<player.location.add[0,1.2,0]> speed:4 script:MP5Damage spread:5.0`

You can actually hit multiple targets with this. But when you hit the same target twice in a single shot the target still gets the same amount of damage as if only one bullet hit him. The problem seems to be that the same entity can't be twice on the `<def[hit_entities]>` list. Is there a way to change that?

**Comment by mcmonkey4eva** [comment]
`gravity, lead, height These 3 options seem to have no effect. I tried it like this, and changing the values has no effect on the bullet:`
Those only take effect if speed: is not specified. They are alternate ways of calculating speed and fire angle.

`speed The speed option works fine up to speed:4 but everything above 4 makes it look like the bullet does not hit the target anymore, but actually it still does. Only the snowball entity flys away in the wrong direction. See this screenshot:`

Minecraft limitation.

`The bigger problem is that the falling blocks get placed as solid blocks in most cases instead of just disappearing. Also they get placed pretty randomly around the hit location. Maybe you can add an option to prevent this?`
That'd be... difficult. I'd like to see it implemented in a script functionally before I try to reimplement in Java.

`Is there anything you can do? Is there any way to change my script so that i can shoot down from rooftops?`
That is strange. Remind me to look into that when I have more time.

`You can actually hit multiple targets with this. But when you hit the same target twice in a single shot the target still gets the same amount of damage as if only one bullet hit him. The problem seems to be that the same entity can't be twice on the <def[hit_entities]>`

Actually, it's a timeout. Minecraft only lets an entity get hurt roughly once a second (might be a different time, like half a second or something). Anything more rapid than the timeout is discounted.
Again, this is Minecraft's doing, not much we can do.

**Comment by GomaTerzu** [comment]
Ok thanks for the answer, let's focus on this part because this is the most relevant issue for gameplay.

´Is there anything you can do? Is there any way to change my script so that i can shoot down from rooftops?´

´That is strange. Remind me to look into that when I have more time.´

**Comment by AnthonyAMC** [comment]
falling_block triggers an EntityChangeBlock event
```
    on entity changes block:
    - if <c.entity.entity_type.is[!=].to[falling_block]> queue clear
    - if <c.entity.fallingblock_material.name.is[==].to[<c.new_material.name>]> {
      - modifyblock <c.location> <c.old_material>
      }
```
Basic concept, would take more effort than that i'm sure, but it's a start.

**Comment by Morphan1** [comment]
@mcmonkey4eva

**Comment by mcmonkey4eva** [comment]
If this is still requested, write up a summary and the requested sample script please. Will reopen when a reply is posted.
